export enum RoleTypeConstant {
  USER = 'USER',
  RECEPTIONIST = 'RECEPTIONIST',
  MEDICAL_LAB_SCIENTIST = 'MEDICAL_LAB_SCIENTIST',
  EMPLOYEE = 'EMPLOYEE',
  PATIENT = 'PATIENT',
  ADMIN = 'ADMIN',
  PATHOLOGIST = 'PATHOLOGIST',
  SUPER_ADMIN = 'SUPER_ADMIN'
}
